services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '1231:1231'
      - '1232:1232'
      - '1233:1233'
      - '1234:1234'
      - '1235:1235'
      - '1236:1236'
      - '1237:1237'
      - '1238:1238'
      - '1239:1239'
      - '1240:1240'
    devices:
      - '/dev/ttyS3:/dev/ttyS3' # Maps COM3 to container
    environment:
      DATABASE_URL: mysql://root:rootpassword@db_container_name:3306/test_chroma
    networks:
      - shared_network
    privileged: true # May be needed for serial port access

networks:
  shared_network:
    external: true
