// export const codeMap = {
//   '0108': 'DEPTH',
//   '0110': 'HOLE_DEPTH',
//   '0112': 'BLOCK_HEIGHT',
//   '0113': 'ROP',
//   '0114': 'HOOKLOAD',
//   '0145': 'SLIPS',
//   '0144': 'ON_BOTTOM',
//   '0120': 'RPM',
//   '0130': 'FLOW',
//   '0121': 'SPP',
//   '0123': 'SPM1',
//   '0124': 'SPM2',
//   '0116': 'WOB',
//   '0118': 'TORQ',
//   '0713': 'INC',
//   '0714': 'AZM',
//   '0715': 'AZMC',
//   '0722': 'GTOT',
//   '0723': 'BTOT',
//   '0724': 'DIP',
//   '0717': 'TF',
//   '0823': 'GAM',
//   '1212': 'methaneC1',
//   '1213': 'ethaneC2',
//   '1214': 'propaneC3',
//   '1215': 'isoButaneC4I',
//   '1216': 'norButaneC4N',
//   '1217': 'isoPentaneC5I',
//   '1218': 'norPentaneC5N',
//   '1219': 'neoPentaneC5E',
//   '1220': 'isoHexaneC6I',
//   '1221': 'norHexaneC6N',
//   '1222': 'carbonDioxide',
//   '1223': 'acetylene',
//   '1224': 'spare112',
//   '1225': 'spare212',
//   '1226': 'spare312',
//   '1227': 'spare412',
//   '1228': 'spare512',
// };

export const codeMap = {
  '0108': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
  '0110': { db_name: 'HOLE_DEPTH', wits_name: 'Hole_Depth' },
  '0112': { db_name: 'BLOCK_HEIGHT', wits_name: 'Block_Height' },
  '0113': { db_name: 'ROP', wits_name: 'Rate_of_Penetration', unit: 'min/m' },
  '0114': { db_name: 'HOOKLOAD', wits_name: 'Hook_Load', unit: 'kg' },
  '0145': { db_name: 'SLIPS', wits_name: 'Slips' },
  '0144': { db_name: 'ON_BOTTOM', wits_name: 'On_Bottom' },
  '0120': { db_name: 'RPM', wits_name: 'RPM', unit: 'rpm' },
  '0130': { db_name: 'FLOW', wits_name: 'Flow' },
  '0121': { db_name: 'SPP', wits_name: 'SPP' },
  '0123': { db_name: 'SPM1', wits_name: 'SPM1' },
  '0124': { db_name: 'SPM2', wits_name: 'SPM2' },
  '0116': { db_name: 'WOB', wits_name: 'WOB' },
  '0118': { db_name: 'TORQ', wits_name: 'TORQ', unit: 'N.m' },
  '0713': { db_name: 'INC', wits_name: 'INC' },
  '0714': { db_name: 'AZM', wits_name: 'AZM' },
  '0715': { db_name: 'AZMC', wits_name: 'AZMC' },
  '0722': { db_name: 'GTOT', wits_name: 'GTOT' },
  '0723': { db_name: 'BTOT', wits_name: 'BTOT' },
  '0724': { db_name: 'DIP', wits_name: 'DIP' },
  '0717': { db_name: 'TF', wits_name: 'TF' },
  '0823': { db_name: 'GAM', wits_name: 'GAM' },
};

// export const codeMap = {
//   '0126': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0108': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0127': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0110': { db_name: 'HOLE_DEPTH', wits_name: 'Hole_Depth', unit: 'm' },
//   '0139': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1208': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0138': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0179': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0174': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0175': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0119': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0166': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0130': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0146': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0137': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0172': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0140': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0116': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0000': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1117': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0114': { db_name: 'HOOKLOAD', wits_name: 'Hook_Load', unit: 'm' },
//   '1116': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1115': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0163': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0121': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0120': { db_name: 'RPM', wits_name: 'RPM', unit: 'rpm' },
//   '0128': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0160': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0112': { db_name: 'BLOCK_HEIGHT', wits_name: 'Block_Height', unit: 'm' },
//   '0159': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0123': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0154': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0124': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0155': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '0125': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1222': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1213': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1212': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1214': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1215': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
//   '1217': { db_name: 'DEPTH', wits_name: 'Depth', unit: 'm' },
// };
